const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon={pin:'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 10.2c0 5.2-8 11-8 11s-8-5.8-8-11a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.6"/></svg>',brief:'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5.5A2.5 2.5 0 0 1 10.5 3h3A2.5 2.5 0 0 1 16 5.5V7M3 12h18"/></svg>',arrow:'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19 19 5M8 5h11v11"/></svg>',users:'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3"/><path d="M3.5 19a5.5 5.5 0 0 1 11 0M16 11a3 3 0 1 0 0-6M16 14a5 5 0 0 1 4.5 5"/></svg>'};
(function fixPublicNavigation(){const routes={'index.html':'/','index.html#about':'/#about','index.html#services':'/#services','index.html#process':'/#process','index.html#jobs':'/#jobs','jobs.html':'/jobs','job.html':'/job','about.html':'/about','contact.html':'/contact','terms.html':'/terms','privacy.html':'/privacy','cookies.html':'/cookies'};document.querySelectorAll('a[href]').forEach(a=>{const raw=(a.getAttribute('href')||'').trim();if(routes[raw])a.setAttribute('href',routes[raw])})})();
let jobs=[];const list=document.querySelector('#job-list'),search=document.querySelector('#search'),locationSelect=document.querySelector('#location'),team=document.querySelector('#team');
function normalize(j){return {id:j.id??j.jobId??j.candidateId??'',title:j.title||'Untitled role',team:j.team||j.category||j.company||'Orrica Edge',summary:j.summary||String(j.description||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,180),location:j.location||'India',type:j.type||j.employmentType||'Full-time',experience:j.experience||'—',openings:j.openings??0}}
function card(j){const href=`/job?id=${encodeURIComponent(j.id)}`;const apply=`/job?id=${encodeURIComponent(j.id)}&apply=1`;return `<article class="job-card"><div><span class="job-team">${esc(j.team)}</span><h3>${esc(j.title)}</h3><p class="job-summary">${esc(j.summary)}</p><div class="job-meta"><span class="meta-item">${icon.pin}${esc(j.location)}</span><span class="meta-item">${icon.brief}${esc(j.type)}</span><span class="meta-item">${icon.arrow}${esc(j.experience)}</span>${j.openings?`<span class="meta-item">${icon.users}${esc(j.openings)} openings</span>`:''}</div></div><div class="job-actions"><a class="view-btn" href="${href}">View job</a><a class="apply-btn" href="${apply}">Apply now <span aria-hidden="true">→</span></a></div></article>`}
function render(){const q=(search.value||'').toLowerCase().trim();const found=jobs.filter(j=>[j.title,j.team,j.location,j.summary].join(' ').toLowerCase().includes(q)&&(!locationSelect.value||j.location===locationSelect.value)&&(!team.value||j.team===team.value));list.innerHTML=found.length?found.map(card).join(''):`<div class="empty">No roles match those filters. Try another search.</div>`;document.querySelector('#results').textContent=`${found.length} open role${found.length===1?'':'s'}`;document.querySelector('#role-count').textContent=String(found.length);document.querySelector('#filterCount').textContent=String((search.value?1:0)+(locationSelect.value?1:0)+(team.value?1:0))}
async function fetchPublicJobs(){
  const urls=['/api/jobs?public=1','https://orrica-edge-backend.onrender.com/api/jobs?public=1'];
  let lastError=null;
  for(const url of urls){
    try{
      const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});
      if(!r.ok) throw new Error(`Jobs API ${r.status}`);
      const data=await r.json();
      const raw=Array.isArray(data)?data:(Array.isArray(data?.jobs)?data.jobs:[]);
      return raw.filter(j=>String(j?.status??'Live').trim().toLowerCase()==='live');
    }catch(error){lastError=error}
  }
  throw lastError||new Error('Jobs API unavailable');
}
fetchPublicJobs().then(raw=>{jobs=raw.map(normalize);for(const prop of ['location','team']){const select=prop==='location'?locationSelect:team;[...new Set(jobs.map(j=>j[prop]).filter(Boolean))].sort().forEach(v=>select.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`))}render()}).catch(()=>{jobs=[];render()});
[search,locationSelect,team].forEach(el=>el.addEventListener('input',render));document.querySelector('#reset').onclick=()=>{search.value='';locationSelect.value='';team.value='';render()};